# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TCIOSListApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TCIOSListApp

  pod 'AFNetworking', '~> 3.0'

  target 'TCIOSListAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TCIOSListAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
